"""Added many-to-many relationship between transactions and categories

Revision ID: bf21eed88287
Revises: b2e432bd58c3
Create Date: 2025-02-04 19:01:41.725553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf21eed88287'
down_revision = 'b2e432bd58c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
